spring:
  application:
    name: project-service
  config:
    import: "optional:configserver:"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  cloud:
    config:
      uri: http://localhost:9090
      name: project-service
server:
  port: 8087