spring:
  application:
    name: infrastructure-service
  kafka:
    bootstrap-servers: 34.124.129.117:9092
    application-id: infrastructure-service
    properties:
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      offset:
        reset: earliest
      commit:
        interval:
          ms: 100

  datasource:
    url: jdbc:postgresql://34.124.129.117:3242/sineth
    username: springdb
    password: ITE2@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jenkins:
  url: http://34.124.129.117:8080
  username: asura
  password: 11281f0b5bbf6654c4a2f2c31897134406
  log:
    topic: jenkins-logs

server:
  port: 8085

name:
  com:
    api:
      token: 2654afc89abd16d01213a0fecadee55cded0ef7b
      username: vannraruos@gmail.com